#!/usr/bin/env python3
"""
Renders an admission-results table directly from the evidence artefacts the
workflows upload. Two tables in the dissertation come from here:

    Table 6.3  attack simulations   .github/workflows/attack-simulations.yml
    Table 6.2  pipeline test cases  .github/workflows/supply-chain-pipeline.yml

Both suites emit the same record schema, so one renderer serves both — the
alternative was a second copy of this file that would drift from the first.

The point of the script is that no result in the dissertation is ever typed by
hand: download the artefacts from the workflow run and render. If a case did not
run, it appears in the table as such rather than silently vanishing.

Usage:
    python3 scripts/attack_table.py attack-results-aws.json attack-results-azure.json
    python3 scripts/attack_table.py --format markdown attack-results-*.json
    python3 scripts/attack_table.py --preset testcases testcase-results-aws.json

Options:
    --format latex|markdown   output format (default: latex)
    --preset attacks|testcases  caption, label and row noun (default: attacks)
    --label <str>             LaTeX label, overriding the preset
    --caption <str>           caption text, overriding the preset
"""
import argparse
import json
import sys

PRESETS = {
    "attacks": {
        "label":   "tab:attacks",
        "caption": "Attack simulation outcomes on {where}. Every row is "
                   "rendered from the evidence artefact uploaded by the attack "
                   "simulation workflow run cited above.",
        "noun":    "scenarios",
        "column":  "Scenario",
        "idcol":   "Class",
    },
    "testcases": {
        "label":   "tab:testcases",
        "caption": "Pipeline admission test outcomes on {where}. Every row is "
                   "rendered from the evidence artefact uploaded by the supply "
                   "chain pipeline run cited above.",
        "noun":    "test cases",
        "column":  "Test case",
        "idcol":   "ID",
    },
}

OBSERVED_LABEL = {
    "DENY":    "Denied",
    "ADMIT":   "Admitted",
    "ERROR":   "Error",
    "NOT_RUN": "Not run",
}


def load(paths):
    runs = []
    for path in paths:
        with open(path) as fh:
            doc = json.load(fh)
        if "scenarios" not in doc or "run" not in doc:
            sys.exit(f"{path}: not an admission-results artefact")
        runs.append(doc)
    if not runs:
        sys.exit("no artefacts given")

    order = [s["scenario"] for s in runs[0]["scenarios"]]
    for doc in runs[1:]:
        if [s["scenario"] for s in doc["scenarios"]] != order:
            sys.exit(
                "artefacts cover different case sets — they come from "
                "different versions of the workflow, or from different suites, "
                "and must not be combined into one table"
            )
    return runs, order


def cell(scenario, latex):
    """Observed outcome for one scenario, emphasised when it was not expected."""
    text = OBSERVED_LABEL.get(scenario["observed_admission"], scenario["observed_admission"])
    if scenario["outcome"] == "PASS":
        return text
    return f"\\textbf{{{text}}}" if latex else f"**{text}**"


def escape(text):
    return text.replace("&", "\\&").replace("_", "\\_").replace("%", "\\%")


def totals(doc):
    """Counts recomputed from the rows being rendered.

    The artefact carries its own totals block; recomputing here means the
    sentence under the table can never disagree with the rows above it. A
    mismatch means the artefact was edited after the run, and says so.
    """
    rows = doc["scenarios"]
    counted = {
        "total": len(rows),
        "pass": sum(1 for s in rows if s["outcome"] == "PASS"),
        "fail": sum(1 for s in rows if s["outcome"] == "FAIL"),
        "error": sum(1 for s in rows if s["outcome"] == "ERROR"),
    }
    recorded = doc.get("totals")
    if recorded and recorded != counted:
        print(
            f"warning: {doc['run']['cloud']} artefact totals {recorded} disagree with "
            f"its own scenario rows {counted} — the artefact has been modified since "
            f"the run; using the rows",
            file=sys.stderr,
        )
    return counted


def render_latex(runs, order, preset):
    clouds = [doc["run"]["cloud"] for doc in runs]
    by_cloud = {doc["run"]["cloud"]: {s["scenario"]: s for s in doc["scenarios"]} for doc in runs}
    first = {s["scenario"]: s for s in runs[0]["scenarios"]}

    out = []
    out.append("% Generated by scripts/attack_table.py — do not edit by hand.")
    out.append("% Source artefacts:")
    for doc in runs:
        r = doc["run"]
        out.append(
            f"%   {r['cloud']}: run {r['run_id']} ({r.get('run_url', 'n/a')}), "
            f"generated {r['generated']}, kyverno {r.get('kyverno_image', 'unknown')}"
        )
    CLUSTER_NAMES = {"aws": "AWS EKS", "azure": "Azure AKS"}
    where = " and ".join(CLUSTER_NAMES.get(c, c) for c in clouds)
    out.append("\\begin{table}[htbp]")
    out.append("  \\centering")
    out.append("  \\caption{" + preset["caption"].format(where=where) + "}")
    out.append(f"  \\label{{{preset['label']}}}")
    cols = " ".join(["p{1.4cm}"] + ["X"] + ["p{1.8cm}"] * (1 + 1 + len(clouds)))
    out.append(f"  \\begin{{tabularx}}{{\\textwidth}}{{{cols}}}")
    out.append("    \\toprule")
    header = [f"\\textbf{{{preset['idcol']}}}", f"\\textbf{{{preset['column']}}}",
              "\\textbf{Requirements}", "\\textbf{Expected}"] + [
                  f"\\textbf{{{CLUSTER_NAMES.get(c, c.upper())}}}" for c in clouds]
    out.append("    " + " & ".join(header) + " \\\\")
    out.append("    \\midrule")

    for sid in order:
        meta = first[sid]
        row = [
            escape(sid),
            escape(meta["title"]),
            escape(", ".join(meta["requirements"])),
            OBSERVED_LABEL.get(meta["expected_admission"], meta["expected_admission"]),
        ] + [cell(by_cloud[c][sid], latex=True) for c in clouds]
        out.append("    " + " & ".join(row) + " \\\\")

    out.append("    \\bottomrule")
    out.append("  \\end{tabularx}")
    out.append("\\end{table}")

    for doc in runs:
        t = totals(doc)
        out.append(
            f"% {doc['run']['cloud']}: {t['pass']}/{t['total']} {preset['noun']} matched the "
            f"expected admission outcome ({t['fail']} unexpected, {t['error']} not run or errored)"
        )
    return "\n".join(out)


def render_markdown(runs, order, preset):
    clouds = [doc["run"]["cloud"] for doc in runs]
    by_cloud = {doc["run"]["cloud"]: {s["scenario"]: s for s in doc["scenarios"]} for doc in runs}
    first = {s["scenario"]: s for s in runs[0]["scenarios"]}

    out = [f"| {preset['idcol']} | {preset['column']} | Requirements | Expected | "
           + " | ".join(c.upper() for c in clouds) + " |"]
    out.append("|" + "---|" * (4 + len(clouds)))
    for sid in order:
        meta = first[sid]
        row = [sid, meta["title"], ", ".join(meta["requirements"]),
               OBSERVED_LABEL.get(meta["expected_admission"], meta["expected_admission"])]
        row += [cell(by_cloud[c][sid], latex=False) for c in clouds]
        out.append("| " + " | ".join(row) + " |")
    out.append("")
    for doc in runs:
        r, t = doc["run"], totals(doc)
        out.append(
            f"{r['cloud']}: {t['pass']}/{t['total']} as expected "
            f"({t['fail']} unexpected, {t['error']} not run or errored) — run {r['run_id']}"
        )
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("artefacts", nargs="+")
    ap.add_argument("--format", choices=["latex", "markdown"], default="latex")
    ap.add_argument("--preset", choices=sorted(PRESETS), default="attacks")
    ap.add_argument("--label")
    ap.add_argument("--caption")
    args = ap.parse_args()

    preset = dict(PRESETS[args.preset])
    if args.label:
        preset["label"] = args.label
    if args.caption:
        preset["caption"] = args.caption

    runs, order = load(args.artefacts)
    runs.sort(key=lambda d: d["run"]["cloud"])
    if args.format == "latex":
        print(render_latex(runs, order, preset))
    else:
        print(render_markdown(runs, order, preset))


if __name__ == "__main__":
    main()
