#!/usr/bin/env bash
# scripts/render-all-tables.sh [aws|azure]
#
# Regenerates every table the dissertation takes from this repository, from the
# committed artefacts under results/, and writes them to:
#
#     results/TABLES-<cloud>.tex   paste-ready LaTeX
#     results/TABLES-<cloud>.md    the same tables, readable in a diff
#
# One command, so the table set cannot drift from the evidence and so a reader
# can regenerate it without knowing which artefact feeds which table. Every
# table carries a provenance comment naming the run, the URL, the Kyverno image
# and the cache state it came from.
#
# If an artefact is missing the table is skipped with a loud note rather than
# silently omitted — a missing table in the output must be visible, because the
# failure mode this repository cares about is a result that quietly disappears.
set -uo pipefail

CLOUD="${1:-aws}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${HERE}"

# This script's own shorthand for the two outputs is tex/md; the renderers take
# latex/markdown. Mapped in one place rather than at each of the eight calls.
fmtflag() { case "$1" in tex) echo latex ;; md) echo markdown ;; *) echo "$1" ;; esac; }

TEX="results/TABLES-${CLOUD}.tex"
MD="results/TABLES-${CLOUD}.md"
MISSING=0

one() {  # one <"tex"|"md"> <section title> <command...>
  local fmt="$1" title="$2"; shift 2
  local out
  if ! out=$("$@" --format "$(fmtflag "${fmt}")" 2>&1); then
    printf '%% !! SKIPPED: %s\n%%    %s\n\n' "${title}" "${out//$'\n'/$'\n'%%    }"
    MISSING=$((MISSING + 1))
    return
  fi
  if [ "${fmt}" = md ]; then
    printf '## %s\n\n```\n%s\n```\n\n' "${title}" "${out}"
  else
    printf '%%%% ── %s ──\n%s\n\n' "${title}" "${out}"
  fi
}

# Resolve a glob to ONE path: the match with the highest run id.
#
# Superseded runs are kept in place on purpose — they are the evidence behind
# the currently-written text — so these globs routinely match several
# directories. A plain `${m[0]}` takes the alphabetically first, which is the
# OLDEST run, and that is how the first version of this script rendered the
# fail-open/fail-closed and evasion tables from the superseded v1.11.4 artefacts
# while reporting success. The run id is printed by every table's own footer, so
# the mistake was visible — but a table set that has to be proofread for which
# run it used is not a table set that can be trusted.
#
# Run ids are monotonically increasing, so the numerically largest is the most
# recent. Ties are impossible; ambiguity is reported rather than resolved
# silently.
g() {
  local matches=() m
  for m in $1; do [ -e "$m" ] && matches+=("$m"); done
  [ ${#matches[@]} -gt 0 ] || return
  if [ ${#matches[@]} -gt 1 ]; then
    printf 'note: %d artefacts matched %s; using the highest run id\n' \
      "${#matches[@]}" "$1" >&2
  fi
  # Sort by the first run-id-shaped number in the path, descending.
  printf '%s\n' "${matches[@]}" \
    | while read -r p; do
        printf '%s\t%s\n' "$(printf '%s' "$p" | grep -oE '[0-9]{8,}' | head -1)" "$p"
      done \
    | sort -rn -k1,1 | head -1 | cut -f2- | tr -d '\n'
}

ATTACK="results/attacks/attack-results-${CLOUD}.json"
TESTCASE="results/testcases/testcase-results-${CLOUD}.json"
EV_MAIN=$(g "results/evasion/${CLOUD}-*-main/evasion-results-${CLOUD}.json")
EV_BRANCH=$(g "results/evasion/${CLOUD}-*-branch/evasion-results-${CLOUD}.json")
FP_OPEN=$(g "results/failure-policy/${CLOUD}-fail-open-3*/attack-results-${CLOUD}.json")
FP_CLOSED=$(g "results/failure-policy/${CLOUD}-fail-closed-3*/attack-results-${CLOUD}.json")
LAT_OFF=$(g "results/latency/${CLOUD}-*-cache-off/latency-${CLOUD}.json")
LAT_ON=$(g "results/latency/${CLOUD}-*-cache-on/latency-${CLOUD}.json")
SZ_OFF=$(g "results/latency/${CLOUD}-*-size-cache-off/size-latency-${CLOUD}.json")
SZ_ON=$(g "results/latency/${CLOUD}-*-size-cache-on/size-latency-${CLOUD}.json")
CC_OFF=$(g "results/concurrency/${CLOUD}-*-cache-off/concurrency-${CLOUD}.json")
CC_ON=$(g "results/concurrency/${CLOUD}-*-cache-on/concurrency-${CLOUD}.json")

# Artefacts collected before the workflow recorded image_verify_cache_enabled
# need the state supplied. The renderer marks such columns as asserted and
# refuses the flag once the artefact records the field itself, so this becomes a
# no-op — and then an error — as soon as these experiments are re-run.
asserted_if_needed() {  # asserted_if_needed <file> -> echoes flags or nothing
  local f="$1"
  [ -n "$f" ] || return
  if [ "$(jq -r '.environment.image_verify_cache_enabled // "unrecorded"' "$f")" = unrecorded ]; then
    printf '%s' "yes"
  fi
}

render() {  # render <fmt> <outfile>
  local fmt="$1"
  {
    if [ "${fmt}" = md ]; then
      echo "# Dissertation tables — ${CLOUD}"
      echo ""
      echo "Generated by \`scripts/render-all-tables.sh ${CLOUD}\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
      echo "Do not edit by hand — regenerate."
      echo ""
    else
      echo "%% Dissertation tables — ${CLOUD}"
      echo "%% Generated by scripts/render-all-tables.sh ${CLOUD} on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
      echo "%% Do not edit by hand — regenerate."
      echo "%%"
      echo "%% Requires in the preamble: \\usepackage{booktabs,tabularx}"
      echo ""
    fi

    if [ -f "${TESTCASE}" ]; then
      one "$fmt" "Table 6.2 — pipeline admission test cases" \
        python3 scripts/attack_table.py --preset testcases "${TESTCASE}"
    fi
    if [ -f "${ATTACK}" ]; then
      one "$fmt" "Table 6.3 — attack simulations" \
        python3 scripts/attack_table.py "${ATTACK}"
    fi
    if [ -n "${FP_OPEN}" ] && [ -n "${FP_CLOSED}" ]; then
      one "$fmt" "Attack simulations under fail-open and fail-closed" \
        python3 scripts/attack_table.py "${FP_OPEN}" "${FP_CLOSED}"
    fi
    if [ -n "${EV_MAIN}" ]; then
      one "$fmt" "Evasion suite — cases available on main (E1-E3)" \
        python3 scripts/attack_table.py --preset evasion "${EV_MAIN}"
    fi
    if [ -n "${EV_BRANCH}" ]; then
      one "$fmt" "Evasion suite — branch dispatch (E4)" \
        python3 scripts/attack_table.py --preset evasion "${EV_BRANCH}"
    fi
    if [ -n "${LAT_OFF}" ] && [ -n "${LAT_ON}" ]; then
      one "$fmt" "Admission overhead by policy configuration and cache state" \
        python3 scripts/latency_table.py --preset overhead "${LAT_OFF}" "${LAT_ON}"
    fi
    if [ -n "${SZ_OFF}" ] && [ -n "${SZ_ON}" ]; then
      if [ -n "$(asserted_if_needed "${SZ_OFF}")" ]; then
        one "$fmt" "Admission cost against image size" \
          python3 scripts/latency_table.py --preset size \
            --cache-state "cache off (cold)" --cache-state "cache on (warm)" \
            "${SZ_OFF}" "${SZ_ON}"
      else
        one "$fmt" "Admission cost against image size" \
          python3 scripts/latency_table.py --preset size "${SZ_OFF}" "${SZ_ON}"
      fi
    fi
    if [ -n "${CC_OFF}" ] && [ -n "${CC_ON}" ]; then
      if [ -n "$(asserted_if_needed "${CC_OFF}")" ]; then
        one "$fmt" "Admission under concurrency" \
          python3 scripts/latency_table.py --preset concurrency \
            --cache-state "cache off (cold)" --cache-state "cache on (warm)" \
            "${CC_OFF}" "${CC_ON}"
      else
        one "$fmt" "Admission under concurrency" \
          python3 scripts/latency_table.py --preset concurrency "${CC_OFF}" "${CC_ON}"
      fi
    fi
  }
}

render tex > "${TEX}"
render md  > "${MD}"

# ── Figures, from the same artefacts ────────────────────────────────────────
# In the same command as the tables on purpose: a figure regenerated separately
# from the table beside it is a figure that can disagree with it, which is
# exactly what defects D11 and D18 were.
mkdir -p results/figures
fig() {  # fig <preset> <requests-csv> <out-basename>
  [ -f "$2" ] || return
  if python3 scripts/latency_charts.py --preset "$1" --requests "$2" --out "$3" >/dev/null 2>&1; then
    echo "  $3.png / .pdf"
  else
    echo "  !! figure failed: $3"
    MISSING=$((MISSING + 1))
  fi
}
LATOFF_CSV=$(g "results/latency/${CLOUD}-*-cache-off/latency-requests-${CLOUD}.csv")
LATON_CSV=$(g "results/latency/${CLOUD}-*-cache-on/latency-requests-${CLOUD}.csv")
SZOFF_CSV=$(g "results/latency/${CLOUD}-*-size-cache-off/size-requests-${CLOUD}.csv")
SZON_CSV=$(g "results/latency/${CLOUD}-*-size-cache-on/size-requests-${CLOUD}.csv")
FIGS=""
[ -n "${LATOFF_CSV}" ] && FIGS="${FIGS}$(fig policy "${LATOFF_CSV}" "results/figures/admission-latency-policy-${CLOUD}-cache-off")\n"
[ -n "${LATON_CSV}"  ] && FIGS="${FIGS}$(fig policy "${LATON_CSV}"  "results/figures/admission-latency-policy-${CLOUD}-cache-on")\n"
[ -n "${SZOFF_CSV}"  ] && FIGS="${FIGS}$(fig size   "${SZOFF_CSV}"  "results/figures/admission-latency-size-${CLOUD}-cache-off")\n"
[ -n "${SZON_CSV}"   ] && FIGS="${FIGS}$(fig size   "${SZON_CSV}"   "results/figures/admission-latency-size-${CLOUD}-cache-on")\n"

echo "Wrote:"
echo "  ${TEX}"
echo "  ${MD}"
[ -n "${FIGS}" ] && printf '%b' "${FIGS}"
if [ "${MISSING}" -gt 0 ]; then
  echo ""
  echo "⚠️  ${MISSING} table(s) could not be rendered — see the '!! SKIPPED' notes."
  echo "    Missing artefacts for ${CLOUD}, or an artefact in an unexpected shape."
fi
